<x-guest-layout>

    <div class="relative bg-white py-16">
        <div class="mx-auto max-w-md px-4 sm:max-w-3xl sm:px-6 lg:px-8 lg:max-w-7xl space-y-8">
            <div class="text-lg max-w-prose mx-auto">
                <div class="prose text-gray-500">
                    <h1>Terms and Conditions</h1>
                    <h3 class="font-semibold tracking-wide uppercase">Promotion Conditions</h3>
                    <p>This promotion is only open to Canon Business Partners and Distribution Partners and their salespeople who are resident in the UK, are aged 18 or over and who are registered as full-time employees of Canon Business Partners who sell Canon devices during the period of the promotion and who have valid email addresses. Partners involvement is based on the Partners selling Canon products, their employees registering on the Canon rewards portal and opting in for the Incentive. Points allocation is based on Sales claims received from valid Partner employees and approved by Canon.</p>
                    <h3 class="font-semibold tracking-wide uppercase">How to Claim?</h3>
                    <h4 class="leading-6 text-indigo-600 text-custom-blue-100">Incentive</h4>
                    <ul>
                        <li>Your company must be a registered and approved Canon participating partner and the Partner employee must opt into the incentive by registering on <a href="https://canon.openchannelrewards.com" class="text-custom-blue-100 hover:text-custom-red-100">https://canon.openchannelrewards.com</a></li>
                        <li>Canon Channel Partner employees residing in the UK must register accurately, and honestly predict, their rate of tax (20% / 40% / 45%) - allowing for all benefits in kind redeemed within the year - for the tax year ending April 5th. Employees can update their tax status 365/24/7 via "My Profile" in the portal.
                        <li>Canon Channel Partner employees then must sell the listed products featured each month on the portal to earn points. Those points can then be redeemed, 'free of tax'* for the Channel Partner and the employee, for rewards featured on the portal.</li>
                        <li>The incentive will run indefinitely, and points can be accumulated and redeemed throughout the promotional period. Points must be redeemed whilst in the employment of a Canon Channel Partner.</li>
                        <li>Canon reserve the right to enforce, by notification, a deadline date for redemptions.</li>
                    </ul>
                    <h4 class="leading-6 text-indigo-600 text-custom-blue-100">Incentive - Tax</h4>
                    <ul>
                        <li>As part of the Canon Rewards Channel Partner incentive, Canon have taken the benefit in kind tax and NIC's burden away from individuals residing in the UK for any rewards claimed. On behalf of Channel Partners and their employees residing in the UK Canon have agreed, with HM Revenue & Customs (HMRC), a Taxed Award Scheme to cover the individual tax liability for any rewards claimed via the Canon Rewards Channel Partner incentive: *
                            <ul>
                                <li>Taxed Award Scheme reference number: TBC</li>
                                <li>Accounts Office reference number - TBC</li>
                            </ul>
                        </li>
                        <li>A Taxed Award Scheme is a voluntary arrangement to pay tax when providing non-cash incentive awards to third party employees. It enables Canon to pay the Channel Partners employees' tax bills on incentive rewards, so that they can receive these rewards 'free of tax'. Canon will pay all the tax due directly to HM Revenue & Customs (HMRC) through their channel marketing agency WorksMC.</li>
                        <li>All Canon ask is that Channel Partner employees, who sell Canon products, register on the Canon Rewards portal, opt in for the incentive scheme and in doing so tell us their country of residence and anticipated tax bracket for the year, to include the value of all benefit in kind awards. If this changes they just need to let us know, by the end of the tax year (April 5th), via ‘My Profile’ on the portal, so Canon can pay the right amount of tax on their behalf.</li>
                        <li>By agreeing to these T&C's, you consent to us sharing your details with HMRC for tax purposes only.</li>
                    </ul>
                    <h3 class="font-semibold tracking-wide uppercase">Points Allocation</h3>
                    <ul>
                        <li>Points will be allocated for sales of the listed product part numbers on the Incentive qualifying products page, and sometimes as part of other Canon funded activities.</li>
                        <li>There will be no retrospective points allocation - sales claims will be verified, approved and points calculated and allocated by Canon based on Sales claims generated by Channel Partner employees.</li>
                        <li>Canon reserves the right to change Product point allocations and the list of qualifying products and part numbers at any time and without notice.</li>
                    </ul>
                    <h3 class="font-semibold tracking-wide uppercase">Reward - Claims</h3>
                    <ul>
                        <li>Reward claims can be made at any time, whilst employed by a Canon Channel Partner, during the promotional period.</li>
                        <li>There will be no cash alternatives. Rewards can only be claimed using current points (not based on future sales).</li>
                        <li>We reserve the right to offer a substitute instead of the desired reward depending on availability.</li>
                        <li>Canon reserves the right to change rewards at any time and without notice.</li>
                    </ul>
                    <h3 class="font-semibold tracking-wide uppercase">Reward - Delivery</h3>
                    <ul>
                        <li>Rewards will be delivered via email or postage depending on the nature of the reward.</li>
                        <li>Delivery will be made at the first available date if agreed to by the individual claiming the reward.</li>
                        <li>By agreeing to these T&C's, you consent to us sharing delivery details (email and postal address) with third parties for delivery purposes only.</li>
                        <li>At the end of each financial year a certificate will be sent to everyone who gets an award under a higher rate scheme. All others can request a certificate. The certificate will show details of the award and the tax paid on it by Canon.</li>
                    </ul>
                    <h3 class="font-semibold tracking-wide uppercase">Management of the Programme</h3>
                    <p>
                        By participating in this programme, Channel and Distribution Partners and registered employees agree to
                        receive email and phone communication from Canon, or its management agency appointed to manage this programme;
                        WorksMC. Canon is the owner of the database where your details will be registered for this programme. Only Canon
                        and its management agency will contact the Canon Channel Partners and individuals concerned. Canon shall have no
                        liability to any participant, and participating Channel Partners shall indemnify Canon against any action, claim,
                        expense or damage brought by a Sales Rep against Canon or any third party arising from, or in connection with this
                        promotion. Unless there is a reasonable and valid reason, the reward should be taken by the individual who submits
                        their choice. Canon accepts full liability for any tax or NIC's liability of either the individual or the
                        Channel/Distribution Partner on rewards claimed because of this promotion in the UK.
                    </p>
                    <p>Any Republic of Ireland (ROI) residents will be responsible and liable for any associated benefit in kind tax payable.</p>
                    <h3 class="font-semibold tracking-wide uppercase">Additional Information</h3>
                    <p>
                        You accept the terms and conditions of this promotion. The promotion is subject to English law and the
                        courts of England and Wales shall have exclusive jurisdiction over any disputes in relation to it.
                        The promoter is Canon. Canon reserves the right to modify or withdraw this promotion at any time.
                        This promotion and/or the terms and conditions herein are void where prohibited or restricted.
                        To participate in the promotion no purchase is necessary, however, to claim, winners must be full
                        time employees of a recognised Canon Channel/Distribution Partner who sells Canon devices.
                        The decision of Canon in relation to any aspect of this programme is final and binding. Questions
                        relating to this programme should be directed to <a href="mailto:canon@openchannelrewards.com" class="text-custom-blue-100 hover:text-custom-red-100">canon@openchannelrewards.com</a>
                    </p>
                    <p class="mt-8">* Excludes residents of the Republic of Ireland (ROI) who are responsible for the payment of any associated benefit in kind taxes.</p>
                </div>

            </div>
        </div>
    </div>

</x-guest-layout>